'use client'
import { useState, useRef, useEffect } from 'react'
import { supabase } from '../../../lib/supabaseClient'

export default function PostGenerator() {
  const [prompt, setPrompt] = useState('')
  const [style, setStyle] = useState('modern')
  const [loading, setLoading] = useState(false)
  const [result, setResult] = useState(null)
  const [user, setUser] = useState(null)
  const canvasRef = useRef(null)

  useEffect(() => {
    const getUser = async () => {
      const { data: { user } } = await supabase.auth.getUser()
      setUser(user)
    }
    getUser()
  }, [])

  const generatePost = async () => {
    setLoading(true)
    
    // Simulate generation time
    await new Promise(resolve => setTimeout(resolve, 2000))
    
    const canvas = canvasRef.current
    if (canvas) {
      const ctx = canvas.getContext('2d')
      
      // Clear canvas
      ctx.fillStyle = '#ffffff'
      ctx.fillRect(0, 0, canvas.width, canvas.height)
      
      // Add background based on style
      if (style === 'modern') {
        ctx.fillStyle = '#3b82f6'
        ctx.fillRect(0, 0, canvas.width, canvas.height / 3)
      } else if (style === 'minimal') {
        ctx.fillStyle = '#f3f4f6'
        ctx.fillRect(0, 0, canvas.width, canvas.height)
      }
      
      // Add text
      ctx.fillStyle = style === 'minimal' ? '#000000' : '#ffffff'
      ctx.font = 'bold 24px Arial'
      ctx.textAlign = 'center'
      ctx.fillText(prompt, canvas.width / 2, canvas.height / 2)
      
      // Add watermark if not pro user
      if (!user || !(await checkProUser(user.id))) {
        ctx.fillStyle = 'rgba(0, 0, 0, 0.3)'
        ctx.font = '12px Arial'
        ctx.fillText('Generated by InstaContentStudio.com', canvas.width / 2, canvas.height - 20)
      }
      
      setResult(canvas.toDataURL())
    }
    
    setLoading(false)
  }

  const checkProUser = async (userId) => {
    const { data } = await supabase
      .from('subscriptions')
      .select('status, plan_id')
      .eq('user_id', userId)
      .single()
    
    return data?.status === 'active' && data?.plan_id === 'pro'
  }

  const saveContent = async () => {
    if (!result) return
    
    const canvas = canvasRef.current
    const blob = await new Promise(resolve => canvas.toBlob(resolve, 'image/png'))
    
    if (!user) {
      // Show signup modal
      alert('Please sign in to save your content!')
      return
    }

    // Upload to Supabase Storage
    const fileName = `post-${Date.now()}.png`
    const { data: uploadData, error } = await supabase.storage
      .from('content-assets')
      .upload(fileName, blob)

    if (error) {
      console.error('Upload error:', error)
      return
    }

    // Get public URL
    const { data: { publicUrl } } = supabase.storage
      .from('content-assets')
      .getPublicUrl(fileName)

    // Save to database
    await supabase.from('content_assets').insert({
      user_id: user.id,
      tool: 'post-generator',
      public_url: publicUrl,
      thumbnail_url: publicUrl,
      metadata: { prompt, style }
    })

    alert('Content saved successfully!')
  }

  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        <h1 className="text-3xl font-bold text-gray-900 mb-2">Post Generator</h1>
        <p className="text-gray-600 mb-8">Create engaging Instagram posts with AI-powered templates</p>

        <div className="grid lg:grid-cols-2 gap-8">
          {/* Input Form */}
          <div className="card">
            <h3 className="text-lg font-semibold mb-4">Create Your Post</h3>
            
            <div className="space-y-4">
              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Post Content
                </label>
                <textarea
                  value={prompt}
                  onChange={(e) => setPrompt(e.target.value)}
                  rows={4}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
                  placeholder="Describe what you want to post about..."
                />
              </div>

              <div>
                <label className="block text-sm font-medium text-gray-700 mb-1">
                  Style
                </label>
                <select
                  value={style}
                  onChange={(e) => setStyle(e.target.value)}
                  className="w-full px-3 py-2 border border-gray-300 rounded-lg focus:ring-primary-500 focus:border-primary-500"
                >
                  <option value="modern">Modern</option>
                  <option value="minimal">Minimal</option>
                  <option value="vibrant">Vibrant</option>
                  <option value="elegant">Elegant</option>
                </select>
              </div>

              <button
                onClick={generatePost}
                disabled={loading || !prompt.trim()}
                className="w-full btn-primary disabled:opacity-50"
              >
                {loading ? 'Generating...' : 'Generate Post'}
              </button>
            </div>
          </div>

          {/* Preview */}
          <div className="card">
            <h3 className="text-lg font-semibold mb-4">Preview</h3>
            
            <div className="aspect-square bg-gray-100 rounded-lg flex items-center justify-center">
              {loading ? (
                <div className="text-center">
                  <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto"></div>
                  <p className="mt-2 text-gray-600">Generating your post...</p>
                </div>
              ) : result ? (
                <div className="text-center">
                  <img src={result} alt="Generated post" className="max-w-full max-h-96 mx-auto" />
                  <button onClick={saveContent} className="btn-primary mt-4">
                    Save Content
                  </button>
                </div>
              ) : (
                <p className="text-gray-500">Your generated post will appear here</p>
              )}
            </div>

            <canvas ref={canvasRef} width={1080} height={1080} className="hidden" />
          </div>
        </div>
      </div>
    </div>
  )
}